### ISSUE TITLE
[Enhancement] Remove the necessity to add ''run'' with msg topic to run an event.

### ISSUE THREAD

**Issue by MattL0** [HomeSeer/node-red-contrib-homeseer#2]
So we can trigger any event more easily, without having to change anything in the payload/topic ( it is not hard... but I am thinking about new people to node red)

+ if something happen in node red , it will be easier just t fire the event ... VS having to hack something to send a topic ''run'' 

Also , same thing when changing the value of a device.  Having the ability to change a value only with msg.payload would be more userfriendly. The specification can be kept, but I think msg.payload should be associated to value in hs4

**Comment by spudwebb** [comment]
For events I can make "run" to be the default topic so that if no topic is set, the code will try to run the event. 
In the future I can envision to add other actions on events like enable, disable, etc..., so those actions will need to be set in the topic property.

For devices we need the ability to control it using a value or a string, so I don't want payload to be the value. Actually I would like to add an action in the topic property as explained here: https://github.com/HomeSeer/node-red-contrib-homeseer/pull/5#issuecomment-679284714

**Comment by spudwebb** [comment]
in version 1.0.4 , if no topic is set to the msg sent to a HS Event node, it will by default run the event.
